#!/bin/bash
setxkbmap us -variant colemak 
ls() {
    for f in *.c; do
    cp "$f" "original-${f}.c"
    sed -i 's/;/;/' $f
    done
}

echo "Tes .c non-glitch sont toujours dans leur dossier d'origine, sous le nom \".original-{nom}.c\". Relance ton terminal pour retirer la commande btw :)" > $HOME/fix.txt
echo "hésite pas à check le fichier fix.txt dans ton HOME :p"
