#!/bin/bash

#wals=()
#for file in $1
#	do wals=("${wals[@]}" "$file")
#       echo $wals[@]
#done

wallpaper=$(find $1 -type f -name "*.jpg" -o -name "*.png" -o -name "*.jpeg" | shuf -n 1)
feh -g +0 -g +380 --bg-fill $wallpaper
