#!/bin/bash
if [[ !($1) ]]; then
    echo "Specify a file or folder !"
    exit
fi
pkill polybar
/home/kani/.config/polybar/launch.sh &
wal -i $1 --backend $2
pkill feh
feh -g +0 -g +380 --bg-fill "$(< .cache/wal/wal)"
#/home/kani/.config/polybar/shades/scripts/pywal.sh "$(< .cache/wal/wal)"

