#!/usr/bin/zsh
var=`setxkbmap -query | egrep 'variant' | wc -l`
if [[ $var == "1" ]]
then
	setxkbmap us
	notify-send "Keyboard Layout" "US-EN"
else
	setxkbmap us -variant intl
	notify-send "Keyboard Layout" "US-INTL"
fi
